baseURL = "https://egosphe.re/"
languageCode = "en-gb"
title = "Egosphere"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Alex E"
    description = "the occasionally coherent creations of one Alex E, human"
    githubUsername = "thisisjaid"
    accent = "#0088b3"
    showBorder = true
    backgroundColor = "#303030"
    font = "Oxygen" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "python", "bash", "json"]
    favicon = "favicon-32x32.png"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/ramblings/"
    name = "Ramblings"
    weight = 2

[[menu.main]]
    url = "/wanderings/"
    name = "Wanderings"
    weight = 2

[[menu.main]]
    url = "/things/"
    name = "Things I made"
    weight = 4

[[menu.main]]
    url = "/designations/"
    name = "Designations"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://github.com/thisisjaid/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/quasi_quasar/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/ealex/"
    name = "linkedin"
    weight = 4
